version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestTemp2Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestTemp2Project
  gitUsername: PoojaAnandGit
  gitBranch: main
